/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRecordingsRouteImport } from './routes/_authed/recordings'
import { Route as AuthedPostsRouteImport } from './routes/_authed/posts'
import { Route as AuthedDrugsRouteImport } from './routes/_authed/drugs'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedPatientsIndexRouteImport } from './routes/_authed/patients.index'
import { Route as AuthedSessionAppointmentIdRouteImport } from './routes/_authed/session.$appointmentId'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'
import { Route as AuthedPatientsPatientIdRouteImport } from './routes/_authed/patients.$patientId'
import { Route as AuthedSessionAppointmentIdTherapyRouteImport } from './routes/_authed/session.$appointmentId.therapy'
import { Route as AuthedSessionAppointmentIdTestOrdersRouteImport } from './routes/_authed/session.$appointmentId.test-orders'
import { Route as AuthedSessionAppointmentIdStatusRouteImport } from './routes/_authed/session.$appointmentId.status'
import { Route as AuthedSessionAppointmentIdResultsRouteImport } from './routes/_authed/session.$appointmentId.results'
import { Route as AuthedSessionAppointmentIdReferralRouteImport } from './routes/_authed/session.$appointmentId.referral'
import { Route as AuthedSessionAppointmentIdPatientRouteImport } from './routes/_authed/session.$appointmentId.patient'
import { Route as AuthedSessionAppointmentIdDocumentsRouteImport } from './routes/_authed/session.$appointmentId.documents'
import { Route as AuthedSessionAppointmentIdDiagnosisRouteImport } from './routes/_authed/session.$appointmentId.diagnosis'
import { Route as AuthedSessionAppointmentIdAnamnesisRouteImport } from './routes/_authed/session.$appointmentId.anamnesis'
import { Route as AuthedPatientsPatientIdHistoryRouteImport } from './routes/_authed/patients.$patientId.history'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRecordingsRoute = AuthedRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsRoute = AuthedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDrugsRoute = AuthedDrugsRouteImport.update({
  id: '/drugs',
  path: '/drugs',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRoute,
} as any)
const AuthedPatientsIndexRoute = AuthedPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSessionAppointmentIdRoute =
  AuthedSessionAppointmentIdRouteImport.update({
    id: '/session/$appointmentId',
    path: '/session/$appointmentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRoute,
} as any)
const AuthedPatientsPatientIdRoute = AuthedPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSessionAppointmentIdTherapyRoute =
  AuthedSessionAppointmentIdTherapyRouteImport.update({
    id: '/therapy',
    path: '/therapy',
    getParentRoute: () => AuthedSessionAppointmentIdRoute,
  } as any)
const AuthedSessionAppointmentIdTestOrdersRoute =
  AuthedSessionAppointmentIdTestOrdersRouteImport.update({
    id: '/test-orders',
    path: '/test-orders',
    getParentRoute: () => AuthedSessionAppointmentIdRoute,
  } as any)
const AuthedSessionAppointmentIdStatusRoute =
  AuthedSessionAppointmentIdStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthedSessionAppointmentIdRoute,
  } as any)
const AuthedSessionAppointmentIdResultsRoute =
  AuthedSessionAppointmentIdResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthedSessionAppointmentIdRoute,
  } as any)
const AuthedSessionAppointmentIdReferralRoute =
  AuthedSessionAppointmentIdReferralRouteImport.update({
    id: '/referral',
    path: '/referral',
    getParentRoute: () => AuthedSessionAppointmentIdRoute,
  } as any)
const AuthedSessionAppointmentIdPatientRoute =
  AuthedSessionAppointmentIdPatientRouteImport.update({
    id: '/patient',
    path: '/patient',
    getParentRoute: () => AuthedSessionAppointmentIdRoute,
  } as any)
const AuthedSessionAppointmentIdDocumentsRoute =
  AuthedSessionAppointmentIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthedSessionAppointmentIdRoute,
  } as any)
const AuthedSessionAppointmentIdDiagnosisRoute =
  AuthedSessionAppointmentIdDiagnosisRouteImport.update({
    id: '/diagnosis',
    path: '/diagnosis',
    getParentRoute: () => AuthedSessionAppointmentIdRoute,
  } as any)
const AuthedSessionAppointmentIdAnamnesisRoute =
  AuthedSessionAppointmentIdAnamnesisRouteImport.update({
    id: '/anamnesis',
    path: '/anamnesis',
    getParentRoute: () => AuthedSessionAppointmentIdRoute,
  } as any)
const AuthedPatientsPatientIdHistoryRoute =
  AuthedPatientsPatientIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/drugs': typeof AuthedDrugsRoute
  '/posts': typeof AuthedPostsRouteWithChildren
  '/recordings': typeof AuthedRecordingsRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdRouteWithChildren
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/session/$appointmentId': typeof AuthedSessionAppointmentIdRouteWithChildren
  '/patients/': typeof AuthedPatientsIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/patients/$patientId/history': typeof AuthedPatientsPatientIdHistoryRoute
  '/session/$appointmentId/anamnesis': typeof AuthedSessionAppointmentIdAnamnesisRoute
  '/session/$appointmentId/diagnosis': typeof AuthedSessionAppointmentIdDiagnosisRoute
  '/session/$appointmentId/documents': typeof AuthedSessionAppointmentIdDocumentsRoute
  '/session/$appointmentId/patient': typeof AuthedSessionAppointmentIdPatientRoute
  '/session/$appointmentId/referral': typeof AuthedSessionAppointmentIdReferralRoute
  '/session/$appointmentId/results': typeof AuthedSessionAppointmentIdResultsRoute
  '/session/$appointmentId/status': typeof AuthedSessionAppointmentIdStatusRoute
  '/session/$appointmentId/test-orders': typeof AuthedSessionAppointmentIdTestOrdersRoute
  '/session/$appointmentId/therapy': typeof AuthedSessionAppointmentIdTherapyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/drugs': typeof AuthedDrugsRoute
  '/recordings': typeof AuthedRecordingsRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdRouteWithChildren
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/session/$appointmentId': typeof AuthedSessionAppointmentIdRouteWithChildren
  '/patients': typeof AuthedPatientsIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/patients/$patientId/history': typeof AuthedPatientsPatientIdHistoryRoute
  '/session/$appointmentId/anamnesis': typeof AuthedSessionAppointmentIdAnamnesisRoute
  '/session/$appointmentId/diagnosis': typeof AuthedSessionAppointmentIdDiagnosisRoute
  '/session/$appointmentId/documents': typeof AuthedSessionAppointmentIdDocumentsRoute
  '/session/$appointmentId/patient': typeof AuthedSessionAppointmentIdPatientRoute
  '/session/$appointmentId/referral': typeof AuthedSessionAppointmentIdReferralRoute
  '/session/$appointmentId/results': typeof AuthedSessionAppointmentIdResultsRoute
  '/session/$appointmentId/status': typeof AuthedSessionAppointmentIdStatusRoute
  '/session/$appointmentId/test-orders': typeof AuthedSessionAppointmentIdTestOrdersRoute
  '/session/$appointmentId/therapy': typeof AuthedSessionAppointmentIdTherapyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/drugs': typeof AuthedDrugsRoute
  '/_authed/posts': typeof AuthedPostsRouteWithChildren
  '/_authed/recordings': typeof AuthedRecordingsRoute
  '/_authed/patients/$patientId': typeof AuthedPatientsPatientIdRouteWithChildren
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/session/$appointmentId': typeof AuthedSessionAppointmentIdRouteWithChildren
  '/_authed/patients/': typeof AuthedPatientsIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/patients/$patientId/history': typeof AuthedPatientsPatientIdHistoryRoute
  '/_authed/session/$appointmentId/anamnesis': typeof AuthedSessionAppointmentIdAnamnesisRoute
  '/_authed/session/$appointmentId/diagnosis': typeof AuthedSessionAppointmentIdDiagnosisRoute
  '/_authed/session/$appointmentId/documents': typeof AuthedSessionAppointmentIdDocumentsRoute
  '/_authed/session/$appointmentId/patient': typeof AuthedSessionAppointmentIdPatientRoute
  '/_authed/session/$appointmentId/referral': typeof AuthedSessionAppointmentIdReferralRoute
  '/_authed/session/$appointmentId/results': typeof AuthedSessionAppointmentIdResultsRoute
  '/_authed/session/$appointmentId/status': typeof AuthedSessionAppointmentIdStatusRoute
  '/_authed/session/$appointmentId/test-orders': typeof AuthedSessionAppointmentIdTestOrdersRoute
  '/_authed/session/$appointmentId/therapy': typeof AuthedSessionAppointmentIdTherapyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/drugs'
    | '/posts'
    | '/recordings'
    | '/patients/$patientId'
    | '/posts/$postId'
    | '/session/$appointmentId'
    | '/patients/'
    | '/posts/'
    | '/patients/$patientId/history'
    | '/session/$appointmentId/anamnesis'
    | '/session/$appointmentId/diagnosis'
    | '/session/$appointmentId/documents'
    | '/session/$appointmentId/patient'
    | '/session/$appointmentId/referral'
    | '/session/$appointmentId/results'
    | '/session/$appointmentId/status'
    | '/session/$appointmentId/test-orders'
    | '/session/$appointmentId/therapy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/drugs'
    | '/recordings'
    | '/patients/$patientId'
    | '/posts/$postId'
    | '/session/$appointmentId'
    | '/patients'
    | '/posts'
    | '/patients/$patientId/history'
    | '/session/$appointmentId/anamnesis'
    | '/session/$appointmentId/diagnosis'
    | '/session/$appointmentId/documents'
    | '/session/$appointmentId/patient'
    | '/session/$appointmentId/referral'
    | '/session/$appointmentId/results'
    | '/session/$appointmentId/status'
    | '/session/$appointmentId/test-orders'
    | '/session/$appointmentId/therapy'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/drugs'
    | '/_authed/posts'
    | '/_authed/recordings'
    | '/_authed/patients/$patientId'
    | '/_authed/posts/$postId'
    | '/_authed/session/$appointmentId'
    | '/_authed/patients/'
    | '/_authed/posts/'
    | '/_authed/patients/$patientId/history'
    | '/_authed/session/$appointmentId/anamnesis'
    | '/_authed/session/$appointmentId/diagnosis'
    | '/_authed/session/$appointmentId/documents'
    | '/_authed/session/$appointmentId/patient'
    | '/_authed/session/$appointmentId/referral'
    | '/_authed/session/$appointmentId/results'
    | '/_authed/session/$appointmentId/status'
    | '/_authed/session/$appointmentId/test-orders'
    | '/_authed/session/$appointmentId/therapy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/recordings': {
      id: '/_authed/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof AuthedRecordingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/drugs': {
      id: '/_authed/drugs'
      path: '/drugs'
      fullPath: '/drugs'
      preLoaderRoute: typeof AuthedDrugsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
    '/_authed/patients/': {
      id: '/_authed/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthedPatientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/session/$appointmentId': {
      id: '/_authed/session/$appointmentId'
      path: '/session/$appointmentId'
      fullPath: '/session/$appointmentId'
      preLoaderRoute: typeof AuthedSessionAppointmentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
    '/_authed/patients/$patientId': {
      id: '/_authed/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthedPatientsPatientIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/session/$appointmentId/therapy': {
      id: '/_authed/session/$appointmentId/therapy'
      path: '/therapy'
      fullPath: '/session/$appointmentId/therapy'
      preLoaderRoute: typeof AuthedSessionAppointmentIdTherapyRouteImport
      parentRoute: typeof AuthedSessionAppointmentIdRoute
    }
    '/_authed/session/$appointmentId/test-orders': {
      id: '/_authed/session/$appointmentId/test-orders'
      path: '/test-orders'
      fullPath: '/session/$appointmentId/test-orders'
      preLoaderRoute: typeof AuthedSessionAppointmentIdTestOrdersRouteImport
      parentRoute: typeof AuthedSessionAppointmentIdRoute
    }
    '/_authed/session/$appointmentId/status': {
      id: '/_authed/session/$appointmentId/status'
      path: '/status'
      fullPath: '/session/$appointmentId/status'
      preLoaderRoute: typeof AuthedSessionAppointmentIdStatusRouteImport
      parentRoute: typeof AuthedSessionAppointmentIdRoute
    }
    '/_authed/session/$appointmentId/results': {
      id: '/_authed/session/$appointmentId/results'
      path: '/results'
      fullPath: '/session/$appointmentId/results'
      preLoaderRoute: typeof AuthedSessionAppointmentIdResultsRouteImport
      parentRoute: typeof AuthedSessionAppointmentIdRoute
    }
    '/_authed/session/$appointmentId/referral': {
      id: '/_authed/session/$appointmentId/referral'
      path: '/referral'
      fullPath: '/session/$appointmentId/referral'
      preLoaderRoute: typeof AuthedSessionAppointmentIdReferralRouteImport
      parentRoute: typeof AuthedSessionAppointmentIdRoute
    }
    '/_authed/session/$appointmentId/patient': {
      id: '/_authed/session/$appointmentId/patient'
      path: '/patient'
      fullPath: '/session/$appointmentId/patient'
      preLoaderRoute: typeof AuthedSessionAppointmentIdPatientRouteImport
      parentRoute: typeof AuthedSessionAppointmentIdRoute
    }
    '/_authed/session/$appointmentId/documents': {
      id: '/_authed/session/$appointmentId/documents'
      path: '/documents'
      fullPath: '/session/$appointmentId/documents'
      preLoaderRoute: typeof AuthedSessionAppointmentIdDocumentsRouteImport
      parentRoute: typeof AuthedSessionAppointmentIdRoute
    }
    '/_authed/session/$appointmentId/diagnosis': {
      id: '/_authed/session/$appointmentId/diagnosis'
      path: '/diagnosis'
      fullPath: '/session/$appointmentId/diagnosis'
      preLoaderRoute: typeof AuthedSessionAppointmentIdDiagnosisRouteImport
      parentRoute: typeof AuthedSessionAppointmentIdRoute
    }
    '/_authed/session/$appointmentId/anamnesis': {
      id: '/_authed/session/$appointmentId/anamnesis'
      path: '/anamnesis'
      fullPath: '/session/$appointmentId/anamnesis'
      preLoaderRoute: typeof AuthedSessionAppointmentIdAnamnesisRouteImport
      parentRoute: typeof AuthedSessionAppointmentIdRoute
    }
    '/_authed/patients/$patientId/history': {
      id: '/_authed/patients/$patientId/history'
      path: '/history'
      fullPath: '/patients/$patientId/history'
      preLoaderRoute: typeof AuthedPatientsPatientIdHistoryRouteImport
      parentRoute: typeof AuthedPatientsPatientIdRoute
    }
  }
}

interface AuthedPostsRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteChildren: AuthedPostsRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteWithChildren = AuthedPostsRoute._addFileChildren(
  AuthedPostsRouteChildren,
)

interface AuthedPatientsPatientIdRouteChildren {
  AuthedPatientsPatientIdHistoryRoute: typeof AuthedPatientsPatientIdHistoryRoute
}

const AuthedPatientsPatientIdRouteChildren: AuthedPatientsPatientIdRouteChildren =
  {
    AuthedPatientsPatientIdHistoryRoute: AuthedPatientsPatientIdHistoryRoute,
  }

const AuthedPatientsPatientIdRouteWithChildren =
  AuthedPatientsPatientIdRoute._addFileChildren(
    AuthedPatientsPatientIdRouteChildren,
  )

interface AuthedSessionAppointmentIdRouteChildren {
  AuthedSessionAppointmentIdAnamnesisRoute: typeof AuthedSessionAppointmentIdAnamnesisRoute
  AuthedSessionAppointmentIdDiagnosisRoute: typeof AuthedSessionAppointmentIdDiagnosisRoute
  AuthedSessionAppointmentIdDocumentsRoute: typeof AuthedSessionAppointmentIdDocumentsRoute
  AuthedSessionAppointmentIdPatientRoute: typeof AuthedSessionAppointmentIdPatientRoute
  AuthedSessionAppointmentIdReferralRoute: typeof AuthedSessionAppointmentIdReferralRoute
  AuthedSessionAppointmentIdResultsRoute: typeof AuthedSessionAppointmentIdResultsRoute
  AuthedSessionAppointmentIdStatusRoute: typeof AuthedSessionAppointmentIdStatusRoute
  AuthedSessionAppointmentIdTestOrdersRoute: typeof AuthedSessionAppointmentIdTestOrdersRoute
  AuthedSessionAppointmentIdTherapyRoute: typeof AuthedSessionAppointmentIdTherapyRoute
}

const AuthedSessionAppointmentIdRouteChildren: AuthedSessionAppointmentIdRouteChildren =
  {
    AuthedSessionAppointmentIdAnamnesisRoute:
      AuthedSessionAppointmentIdAnamnesisRoute,
    AuthedSessionAppointmentIdDiagnosisRoute:
      AuthedSessionAppointmentIdDiagnosisRoute,
    AuthedSessionAppointmentIdDocumentsRoute:
      AuthedSessionAppointmentIdDocumentsRoute,
    AuthedSessionAppointmentIdPatientRoute:
      AuthedSessionAppointmentIdPatientRoute,
    AuthedSessionAppointmentIdReferralRoute:
      AuthedSessionAppointmentIdReferralRoute,
    AuthedSessionAppointmentIdResultsRoute:
      AuthedSessionAppointmentIdResultsRoute,
    AuthedSessionAppointmentIdStatusRoute:
      AuthedSessionAppointmentIdStatusRoute,
    AuthedSessionAppointmentIdTestOrdersRoute:
      AuthedSessionAppointmentIdTestOrdersRoute,
    AuthedSessionAppointmentIdTherapyRoute:
      AuthedSessionAppointmentIdTherapyRoute,
  }

const AuthedSessionAppointmentIdRouteWithChildren =
  AuthedSessionAppointmentIdRoute._addFileChildren(
    AuthedSessionAppointmentIdRouteChildren,
  )

interface AuthedRouteChildren {
  AuthedDrugsRoute: typeof AuthedDrugsRoute
  AuthedPostsRoute: typeof AuthedPostsRouteWithChildren
  AuthedRecordingsRoute: typeof AuthedRecordingsRoute
  AuthedPatientsPatientIdRoute: typeof AuthedPatientsPatientIdRouteWithChildren
  AuthedSessionAppointmentIdRoute: typeof AuthedSessionAppointmentIdRouteWithChildren
  AuthedPatientsIndexRoute: typeof AuthedPatientsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDrugsRoute: AuthedDrugsRoute,
  AuthedPostsRoute: AuthedPostsRouteWithChildren,
  AuthedRecordingsRoute: AuthedRecordingsRoute,
  AuthedPatientsPatientIdRoute: AuthedPatientsPatientIdRouteWithChildren,
  AuthedSessionAppointmentIdRoute: AuthedSessionAppointmentIdRouteWithChildren,
  AuthedPatientsIndexRoute: AuthedPatientsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
