/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRecordingsRouteImport } from './routes/_authed/recordings'
import { Route as AuthedPostsRouteImport } from './routes/_authed/posts'
import { Route as AuthedPostsIndexRouteImport } from './routes/_authed/posts.index'
import { Route as AuthedPatientsIndexRouteImport } from './routes/_authed/patients.index'
import { Route as AuthedSessionAppointmentIdRouteImport } from './routes/_authed/session.$appointmentId'
import { Route as AuthedPostsPostIdRouteImport } from './routes/_authed/posts.$postId'
import { Route as AuthedPatientsPatientIdRouteImport } from './routes/_authed/patients.$patientId'
import { Route as AuthedSessionResultsAppointmentIdRouteImport } from './routes/_authed/session.results.$appointmentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRecordingsRoute = AuthedRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsRoute = AuthedPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPostsIndexRoute = AuthedPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPostsRoute,
} as any)
const AuthedPatientsIndexRoute = AuthedPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSessionAppointmentIdRoute =
  AuthedSessionAppointmentIdRouteImport.update({
    id: '/session/$appointmentId',
    path: '/session/$appointmentId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedPostsPostIdRoute = AuthedPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthedPostsRoute,
} as any)
const AuthedPatientsPatientIdRoute = AuthedPatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSessionResultsAppointmentIdRoute =
  AuthedSessionResultsAppointmentIdRouteImport.update({
    id: '/session/results/$appointmentId',
    path: '/session/results/$appointmentId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/posts': typeof AuthedPostsRouteWithChildren
  '/recordings': typeof AuthedRecordingsRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/session/$appointmentId': typeof AuthedSessionAppointmentIdRoute
  '/patients/': typeof AuthedPatientsIndexRoute
  '/posts/': typeof AuthedPostsIndexRoute
  '/session/results/$appointmentId': typeof AuthedSessionResultsAppointmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/recordings': typeof AuthedRecordingsRoute
  '/patients/$patientId': typeof AuthedPatientsPatientIdRoute
  '/posts/$postId': typeof AuthedPostsPostIdRoute
  '/session/$appointmentId': typeof AuthedSessionAppointmentIdRoute
  '/patients': typeof AuthedPatientsIndexRoute
  '/posts': typeof AuthedPostsIndexRoute
  '/session/results/$appointmentId': typeof AuthedSessionResultsAppointmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/_authed/posts': typeof AuthedPostsRouteWithChildren
  '/_authed/recordings': typeof AuthedRecordingsRoute
  '/_authed/patients/$patientId': typeof AuthedPatientsPatientIdRoute
  '/_authed/posts/$postId': typeof AuthedPostsPostIdRoute
  '/_authed/session/$appointmentId': typeof AuthedSessionAppointmentIdRoute
  '/_authed/patients/': typeof AuthedPatientsIndexRoute
  '/_authed/posts/': typeof AuthedPostsIndexRoute
  '/_authed/session/results/$appointmentId': typeof AuthedSessionResultsAppointmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/posts'
    | '/recordings'
    | '/patients/$patientId'
    | '/posts/$postId'
    | '/session/$appointmentId'
    | '/patients/'
    | '/posts/'
    | '/session/results/$appointmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/signup'
    | '/recordings'
    | '/patients/$patientId'
    | '/posts/$postId'
    | '/session/$appointmentId'
    | '/patients'
    | '/posts'
    | '/session/results/$appointmentId'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/_authed/posts'
    | '/_authed/recordings'
    | '/_authed/patients/$patientId'
    | '/_authed/posts/$postId'
    | '/_authed/session/$appointmentId'
    | '/_authed/patients/'
    | '/_authed/posts/'
    | '/_authed/session/results/$appointmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/recordings': {
      id: '/_authed/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof AuthedRecordingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts': {
      id: '/_authed/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthedPostsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/': {
      id: '/_authed/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthedPostsIndexRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
    '/_authed/patients/': {
      id: '/_authed/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthedPatientsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/session/$appointmentId': {
      id: '/_authed/session/$appointmentId'
      path: '/session/$appointmentId'
      fullPath: '/session/$appointmentId'
      preLoaderRoute: typeof AuthedSessionAppointmentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/posts/$postId': {
      id: '/_authed/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthedPostsPostIdRouteImport
      parentRoute: typeof AuthedPostsRoute
    }
    '/_authed/patients/$patientId': {
      id: '/_authed/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthedPatientsPatientIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/session/results/$appointmentId': {
      id: '/_authed/session/results/$appointmentId'
      path: '/session/results/$appointmentId'
      fullPath: '/session/results/$appointmentId'
      preLoaderRoute: typeof AuthedSessionResultsAppointmentIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedPostsRouteChildren {
  AuthedPostsPostIdRoute: typeof AuthedPostsPostIdRoute
  AuthedPostsIndexRoute: typeof AuthedPostsIndexRoute
}

const AuthedPostsRouteChildren: AuthedPostsRouteChildren = {
  AuthedPostsPostIdRoute: AuthedPostsPostIdRoute,
  AuthedPostsIndexRoute: AuthedPostsIndexRoute,
}

const AuthedPostsRouteWithChildren = AuthedPostsRoute._addFileChildren(
  AuthedPostsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedPostsRoute: typeof AuthedPostsRouteWithChildren
  AuthedRecordingsRoute: typeof AuthedRecordingsRoute
  AuthedPatientsPatientIdRoute: typeof AuthedPatientsPatientIdRoute
  AuthedSessionAppointmentIdRoute: typeof AuthedSessionAppointmentIdRoute
  AuthedPatientsIndexRoute: typeof AuthedPatientsIndexRoute
  AuthedSessionResultsAppointmentIdRoute: typeof AuthedSessionResultsAppointmentIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPostsRoute: AuthedPostsRouteWithChildren,
  AuthedRecordingsRoute: AuthedRecordingsRoute,
  AuthedPatientsPatientIdRoute: AuthedPatientsPatientIdRoute,
  AuthedSessionAppointmentIdRoute: AuthedSessionAppointmentIdRoute,
  AuthedPatientsIndexRoute: AuthedPatientsIndexRoute,
  AuthedSessionResultsAppointmentIdRoute:
    AuthedSessionResultsAppointmentIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
